---
# ============================================================
# Setup MySQL Server (Debian 13)
# Used for: Apache backend + Scoring Engine
# Author: William Walker (Grey Team)
# ============================================================

- name: Setup MySQL Server (Debian 13)
  hosts: mysql_servers
  become: true
  gather_facts: true

  vars_files:
    - ../../../vars/linux/common.yml
    - ../../../vars/linux/mysql.yml

  roles:
    - linux/common

  tasks:
    - import_role:
        name: linux/mysql
        tasks_from: main.yml

