---

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true

- name: Restart Systemd Daemon
  ansible.builtin.shell: "systemctl daemon-reload"
  become: true
    