#   LINUX HOSTS

[openssh_servers]
scp-openssh-01 ansible_host=10.10.10.138

[openvpn_servers]
scp-openvpn-01 ansible_host=10.10.10.104

[mysql_servers]
scp-mysql-01 ansible_host=10.10.10.102

[scoring_host]
scp_scoring01 ansible_host=10.10.10.210

[linux:children]
openssh_servers
openvpn_servers
mysql_servers
scoring_host

[linux:vars]
ansible_user = cyberrange
ansible_password = Cyberrange123!
ansible_connection = ssh
ansible_port = 22
ansible_python_interpreter = /usr/bin/python3
ansible_become_user = root
ansible_become_method = sudo
ansible_ssh_common_args = -o ProxyJump=sshjump@ssh.cyberrange.rit.edu -o StrictHostKeyChecking=no


#   WINDOWS HOSTS

[domain_controllers]
scp_dc01 ansible_host=10.10.10.21

[smb_servers]
scp_smb01 ansible_host=10.10.10.22

[smtp_servers]
scp_smtp01 ansible_host=10.10.10.23

[windows:children]
domain_controllers
smb_servers
smtp_servers

[windows:vars]
ansible_user = cyberrange
ansible_password = Cyberrange123!
ansible_connection = winrm
ansible_winrm_transport = ntlm
ansible_winrm_server_cert_validation = ignore
ansible_port = 5986
ansible_ssh_pass = {{ ansible_password }}
ansible_python_interpreter = /usr/bin/python3
ansible_ssh_common_args = -o ProxyJump=sshjump@ssh.cyberrange.rit.edu -o StrictHostKeyChecking=no
ansible_become_user = Administrator
ansible_become_method = runas



#   WAZUH INFRASTRUCTURE

[wazuh_manager]
scp-wazuh-01 ansible_host=10.10.10.211

[wazuh_manager:vars]
ansible_user = cyberrange
ansible_password = Cyberrange123!
ansible_connection = ssh
ansible_port = 22
ansible_python_interpreter = /usr/bin/python3
ansible_become_user = root
ansible_become_method = sudo
ansible_ssh_common_args = -o ProxyJump=sshjump@ssh.cyberrange.rit.edu -o StrictHostKeyChecking=no

#   Wazuh agent targets — all Blue Team endpoints
[wazuh_linux_agents:children]
openssh_servers
openvpn_servers
mysql_servers

[wazuh_windows_agents:children]
domain_controllers
smb_servers
smtp_servers


#   GLOBAL GROUPS

[all_systems:children]
linux
windows
