---

- name: Setup OpenSSH Server
  hosts: openssh_servers
  gather_facts: yes
  vars_files:
    - ../../vars/linux/common.yml
    - ../../vars/linux/openssh.yml
  
  roles:
    - linux/common
    - linux/openssh