---
- name: Deploy MySQL Flags
  hosts: mysql_servers
  become: true
  gather_facts: true

  vars_files:
    - ../../../vars/linux/common.yml
    - ../../../vars/linux/mysql.yml
    - ../../../vars/linux/flags/mysql.yml

  roles:
    - linux/mysql
