---
- name: Deploy MySQL Flags
  hosts: mysql_servers
  become: true
  vars_files:
    - ../../../vars/linux/common.yml
    - ../../../vars/linux/mysql.yml
    - ../../../vars/linux/flags/mysql.yml

  tasks:
    - import_role:
        name: linux/mysql
        tasks_from: flags.yml
