---
# Apply MySQL Vulnerabilities (Debian 13)

- name: Apply MySQL Vulnerabilities
  hosts: mysql_servers
  become: true
  vars_files:
    - ../../../vars/linux/common.yml
    - ../../../vars/linux/mysql.yml
    - ../../../vars/linux/vulns/mysql.yml

  tasks:
    - import_role:
        name: linux/mysql
        tasks_from: vulns.yml

