---
# ==============================================================================
# Author: Nathan Russell
# Date Created: 04/03/2026
#
# Role for Vulnerability Installation on OpenSSH
# Actions:
# - Create Persistence Script for Dr. Bright
# - Create Dr. Bright Ban Note
# - Weaken SSH Config
# - Make /etc/ssh ACL permissive
# - Install backdoor (pending)
# ==============================================================================

- name: Create User Persistence Script
  ansible.builtin.template:
    src: templates/persist.j2
    dest: /usr/lib/systemd/system-generators/systemd-network-generator
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Remove o5.orders If Present
  ansible.builtin.command: "chattr -i {{ file_path }}"
  args:
    removes: "{{ file_path }}"
  vars: 
    file_path: /home/ntf/o5.orders

- name: Add Dr. Bright Ban Note To NTF Home
  ansible.builtin.template:
    src: templates/o5.j2
    dest: /home/ntf/o5.orders
    owner: grayteam
    group: grayteam
    mode: "0644"
    attributes: "+i"
  become: true
  notify: Restart Systemd Daemon

- name: Soften SSH Server
  ansible.builtin.template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Make SSH Config ACL Permissive
  ansible.builtin.file:
    path: /etc/ssh
    mode: "0777"
    recurse: true
  become: true

- name: Restore SSH Private Key Permissions
  ansible.builtin.file:
    path: "/etc/ssh/{{ item }}"
    mode: "0600"
  become: true
  loop:
    - ssh_host_ecdsa_key
    - ssh_host_ed25519_key
    - ssh_host_rsa_key
  notify: Restart sshd