---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart scp-scorer
  ansible.builtin.systemd:
    name: scp-scorer
    state: restarted
  failed_when: false

- name: Restart scp-dashboard
  ansible.builtin.systemd:
    name: scp-dashboard
    state: restarted
  failed_when: false